In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train_data = pd.read_csv('train.csv')

In [3]:
_corr = train_data.corr()
selected_feature = _corr.index[abs(_corr['SalePrice']) > 0.4] 
_train = train_data[selected_feature]
target = _train['SalePrice']
train_df = _train.drop(['SalePrice'], axis =1)

In [4]:
train_df.fillna(train_df.mean())

,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea
0,7,2003,2003,196.0,856,856,1710,2,8,0,2003.0,2,548
1,6,1976,1976,0.0,1262,1262,1262,2,6,1,1976.0,2,460
2,7,2001,2002,162.0,920,920,1786,2,6,1,2001.0,2,608
3,7,1915,1970,0.0,756,961,1717,1,7,1,1998.0,3,642
4,8,2000,2000,350.0,1145,1145,2198,2,9,1,2000.0,3,836
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,6,1999,2000,0.0,953,953,1647,2,7,1,1999.0,2,460
1456,6,1978,1988,119.0,1542,2073,2073,2,7,2,1978.0,2,500
1457,7,1941,2006,0.0,1152,1188,2340,2,9,2,1941.0,1,252
1458,5,1950,1996,0.0,1078,1078,1078,1,5,0,1950.0,1,240
1459,5,1965,1965,0.0,1256,1256,1256,1,6,0,1965.0,1,276

In [5]:
# 정규화   
normal_df  = (train_df - train_df.mean())/train_df.std() 
normal_df

,OverallQual,YearBuilt,YearRemodAdd,MasVnrArea,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea
0,0.651256,1.050634,0.878367,0.509840,-0.459145,-0.793162,0.370207,0.789470,0.911897,-0.950901,0.992066,0.311618,0.350880
1,-0.071812,0.156680,-0.429430,-0.572637,0.466305,0.257052,-0.482347,0.789470,-0.318574,0.600289,-0.101506,0.311618,-0.060710
2,0.651256,0.984415,0.829930,0.322063,-0.313261,-0.627611,0.514836,0.789470,-0.318574,0.600289,0.911061,0.311618,0.631510
3,0.651256,-1.862993,-0.720051,-0.572637,-0.687089,-0.521555,0.383528,-1.025689,0.296662,0.600289,0.789553,1.649742,0.790533
4,1.374324,0.951306,0.733056,1.360357,0.199611,-0.045596,1.298881,0.789470,1.527133,0.600289,0.870558,1.649742,1.697903
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,-0.071812,0.918196,0.733056,-0.572637,-0.238040,-0.542249,0.250316,0.789470,0.296662,0.600289,0.830055,0.311618,-0.060710
1456,-0.071812,0.222899,0.151813,0.084581,1.104547,2.354894,1.061003,0.789470,0.296662,2.151479,-0.020501,0.311618,0.126376
1457,0.651256,-1.002149,1.023678,-0.572637,0.215567,0.065634,1.569110,0.789470,1.527133,2.151479,-1.519100,-1.026506,-1.033560
1458,-0.794879,-0.704164,0.539309,-0.572637,0.046889,-0.218907,-0.832502,-1.025689,-0.933810,-0.950901,-1.154576,-1.026506,-1.089686
1459,-0.794879,-0.207523,-0.962236,-0.572637,0.452629,0.241532,-0.493765,-1.025689,-0.318574,-0.950901,-0.547036,-1.026506,-0.921308

In [6]:
cate_train = train_data.select_dtypes(include='object')

In [7]:
cate_train

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1,RL,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
2,RL,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
3,RL,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Detchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Abnorml
4,RL,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,...,Attchd,RFn,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1456,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,MnPrv,NaN,WD,Normal
1457,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,...,Attchd,RFn,TA,TA,Y,NaN,GdPrv,Shed,WD,Normal
1458,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,NaN,NaN,NaN,WD,Normal
1459,RL,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,...,Attchd,Fin,TA,TA,Y,NaN,NaN,NaN,WD,Normal

In [8]:
# null 일정 이상 
remove_col = ['Alley' , 'FireplaceQu', 'PoolQC' ,'Fence' ,'MiscFeature']
cate_train = cate_train.drop(remove_col, axis = 1)

In [9]:
cate_train_encode = pd.get_dummies(cate_train)

In [10]:
cate_train_encode.fillna(cate_train_encode.mean())

,MSZoning_C (all),MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,Street_Grvl,Street_Pave,LotShape_IR1,LotShape_IR2,LotShape_IR3,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
2,0,0,0,1,0,0,1,1,0,0,...,0,0,0,1,0,0,0,0,1,0
3,0,0,0,1,0,0,1,1,0,0,...,0,0,0,1,1,0,0,0,0,0
4,0,0,0,1,0,0,1,1,0,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1456,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1457,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1458,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1459,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0

In [11]:
boston_df = pd.merge(cate_train_encode, normal_df, left_index=True, right_index=True)

In [12]:
boston_df

,MSZoning_C (all),MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,Street_Grvl,Street_Pave,LotShape_IR1,LotShape_IR2,LotShape_IR3,...,MasVnrArea,TotalBsmtSF,1stFlrSF,GrLivArea,FullBath,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea
0,0,0,0,1,0,0,1,0,0,0,...,0.509840,-0.459145,-0.793162,0.370207,0.789470,0.911897,-0.950901,0.992066,0.311618,0.350880
1,0,0,0,1,0,0,1,0,0,0,...,-0.572637,0.466305,0.257052,-0.482347,0.789470,-0.318574,0.600289,-0.101506,0.311618,-0.060710
2,0,0,0,1,0,0,1,1,0,0,...,0.322063,-0.313261,-0.627611,0.514836,0.789470,-0.318574,0.600289,0.911061,0.311618,0.631510
3,0,0,0,1,0,0,1,1,0,0,...,-0.572637,-0.687089,-0.521555,0.383528,-1.025689,0.296662,0.600289,0.789553,1.649742,0.790533
4,0,0,0,1,0,0,1,1,0,0,...,1.360357,0.199611,-0.045596,1.298881,0.789470,1.527133,0.600289,0.870558,1.649742,1.697903
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,0,0,0,1,0,0,1,0,0,0,...,-0.572637,-0.238040,-0.542249,0.250316,0.789470,0.296662,0.600289,0.830055,0.311618,-0.060710
1456,0,0,0,1,0,0,1,0,0,0,...,0.084581,1.104547,2.354894,1.061003,0.789470,0.296662,2.151479,-0.020501,0.311618,0.126376
1457,0,0,0,1,0,0,1,0,0,0,...,-0.572637,0.215567,0.065634,1.569110,0.789470,1.527133,2.151479,-1.519100,-1.026506,-1.033560
1458,0,0,0,1,0,0,1,0,0,0,...,-0.572637,0.046889,-0.218907,-0.832502,-1.025689,-0.933810,-0.950901,-1.154576,-1.026506,-1.089686
1459,0,0,0,1,0,0,1,0,0,0,...,-0.572637,0.452629,0.241532,-0.493765,-1.025689,-0.318574,-0.950901,-0.547036,-1.026506,-0.921308

In [13]:
import lightgbm as lgb 
from sklearn.model_selection import train_test_split 

x_train, x_valid, y_train, y_valid = train_test_split(normal_df, target, test_size = 0.01, shuffle = True, random_state=34)
train_ds = lgb.Dataset(x_train, label = y_train)
valid_ds = lgb.Dataset(x_valid, label = y_valid)

ModuleNotFoundError: No module named 'lightgbm'

In [ ]:
params = {'learning_rate': 0.001,
          'max_depth': -1,
          'boosting': 'dart',
          'objective': 'regression',
          'metric': 'mse',
          'is_training_metric': True,
          'num_leaves': 1024,
          'feature_fraction': 0.9,
          'bagging_fraction': 0.7,
          'bagging_freq': 5,
          'seed':2020} 

model = lgb.train(params, train_ds, 5000, valid_ds, verbose_eval=100, early_stopping_rounds=100)

In [ ]:
test_data = pd.read_csv('test.csv')

In [ ]:
selected_feature_test = selected_feature.drop('SalePrice')
_test = test_data[selected_feature_test] 
_test.fillna(_test.mean()) 
normal_test_df  = (_test - _test.mean())/_test.std()  
cate_test = test_data.select_dtypes(include='object')
cate_test = cate_test.drop(remove_col, axis = 1)  
cate_test_encode = pd.get_dummies(cate_test) 
cate_test_encode.fillna(cate_test_encode.mean()) 
test_df = pd.merge(cate_test_encode, normal_test_df, left_index=True, right_index=True)

In [ ]:
sub = pd.read_csv('sample_submission.csv')

In [ ]:
sub['SalePrice'] = model.predict(normal_test_df)

In [ ]:
sub.to_csv('submission.csv', index=False)